server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anastasiiakozlova245/spring-petclinic-microservices-config.git
          default-label: feat/docker-sql
        # Use the File System Backend to avoid git pulling. Enable "native" profile in the Config Server.
        native:
          searchLocations: file:///${GIT_REPO}

